---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.miloapis.com
  resources:
  - platformaccesses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - platformaccesses/status
  verbs:
  - patch
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - serviceaccounts
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - serviceaccounts/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - serviceaccounts/status
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.miloapis.com
  resources:
  - projectcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects/status
  verbs:
  - get
  - update
